### ISSUE TITLE
質問、選択肢のyamlファイルを作る

### ISSUE THREAD

**Issue by ShimaBee** [Yuta1122/credit_diagnosis#6]
質問、選択肢をyamlファイルにまとめる。
選択肢には値もつける。

**Comment by ShimaBee** [comment]
## このissueでやること
一旦、仮でいいので質問を作り、選択肢には値を与えてRails側からNuxtへjson形式で送る。
※ 選択肢に厳密な値を振るタスクは後々立てる。

**Comment by ShimaBee** [comment]
public配下にquestions.ymlというyamlファイルを作り、そこで質問、選択肢、選択肢に振る値を管理していく。

**Comment by ShimaBee** [comment]
簡単に作った
```yaml
- id: 1
  text: "年齢は？"
  choices:
    - "18 ~ 25"
    - "26 ~ 29"
    - "30 ~ 39"
    - "40以上"
  values:
    - age: 0
    - age: 0.3
    - age: 0.7
    - age: 1
- id: 2
  text: "ポイントの貯まりやすさはお気になさいますか？"
  choices:
    - "とても気にする"
    - "気にする"
    - "あまり気にしない"
    - "気にしない"
  values:
    - point: 0
    - point: 0.3
    - point: 0.7
    - point: 1
- id: 3
  text: "マイルの貯まりやすさはお気になさいます？"
  choices:
    - "とても気にする"
    - "気にする"
    - "あまり気にしない"
    - "気にしない"
  values:
    - mile: 0
    - mile: 0.3
    - mile: 0.7
    - mile: 1
- id: 4
  text: "年会費はお気になさいますか？"
  choices:
    - "とても気にする"
    - "気にする"
    - "あまり気にしない"
    - "気にしない"
  values:
    - annual_fee: 0
    - annual_fee: 0.3
    - annual_fee: 0.7
    - annual_fee: 1
```
